### ISSUE TITLE
clearAll() method

### ISSUE THREAD

**Issue by Turbo87** [simplabs/ember-cookies#93]
It looks like we can already `read()` all available cookies and `clear()` a single cookie. For testing purposes it might make sense to have a `clearAll()` method as well, to be able to start an acceptance test without any cookies.

**Comment by marcoow** [comment]
Should that be a test helper maybe? Also we could think about not actually writing any cookies in the `test` environment at all but only store everything in memory so that tests would leave no traces. That would break cases where external JS libraries would actually require a cookie that'd be written through ember-cookies.

**Comment by Turbo87** [comment]
I think a `clearAll()` *might* also be useful outside the context of testing, and making it something different than a simple method on the existing service will increase the complexity of the API quite a bit.

I guess having pluggable adapters as the base for this addon might be an interesting thing to explore given that we already have `browser` and `fastboot` adapters.

**Comment by marcoow** [comment]
> I think a clearAll() might also be useful outside the context of testing

I think this might lead to all kinds of problems potentially as you'd delete all cookies, not just the ones written via ember-cookies (but also ones written by other libraries, set by the server etc.).


> and making it something different than a simple method on the existing service will increase the complexity of the API quite a bit.

Hm, wouldn't that just be

```js
import clearAllCookies from 'ember-cookies';
…
clearAllCookies();
```
> I guess having pluggable adapters as the base for this addon might be an interesting thing to explore given that we already have browser and fastboot adapters.

This would make ember-cookies seriously more complex though so let's see whether we see an actual use case for this.

**Comment by cafreeman** [comment]
+1 on this. I came to the issues here looking for this exact thing because I'm trying to figure out how to reset cookies in `start-app`. Even if there wasn't a `clearAll`, it'd be nice to be able to import `read`, `write`, and `clear` as separate functions independent of the service for use in tests.

**Comment by geekygrappler** [comment]
I've done some investigation. When reading a cookie, we only get the key value pair, and not the path, which means I don't think a `clearAll()` method would be able to pass a cookies path. 

So if we had a cookie which was `test=val` and it was on path `/testing`, a read would give us `{test: val}` and then if we called `clear(test)` it might not be cleared, because we didn't pass the path. If no path is passed the current path is used. e.g. if we were on `/testing/some/other/path` then the `/testing` cookie wouldn't be deleted, if we were on `/testing` it would be.

Is this an acceptable limitation?

**Comment by marcoow** [comment]
I think we should still allow passing options to `clearAll`. The purpose of ember-cookies is really just to provide an API for cookie that works in the browser as well as in FastBoot without doing anything else really or adding anything in addition to that abstraction layer. That said, I think if anyone knows all the options for all the cookies they want to clear we shouldn't stand in the way and let them pass them to `clearAll`.

**Comment by dzbo** [comment]
I've also faced issues with cookies in acceptance tests. Would be great to have that `clearAll` option :)

**Comment by marcoow** [comment]
@geekygrappler: I think you were working on a PR?
